//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcData
    {
        public int ID { get; set; }
        public string Gender { get; set; }
        public decimal Height { get; set; }
        public int Age { get; set; }
        public decimal Weight { get; set; }
        public decimal Activityfactor { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> Carbs { get; set; }
        public Nullable<decimal> Protein { get; set; }
        public Nullable<decimal> KcalResult { get; set; }
        public Nullable<decimal> KcalPlusMinus { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> RegID { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
