//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TreningEntities : DbContext
    {
        public TreningEntities()
            : base("name=TreningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesstokens> accesstokens { get; set; }
        public virtual DbSet<CalcData> CalcData { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Trainingprogram> Trainingprogram { get; set; }
        public virtual DbSet<UserRegistration> UserRegistration { get; set; }
    }
}
