//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainingprogram
    {
        public int ID { get; set; }
        public string TrainingExperience { get; set; }
        public string Trainingdays { get; set; }
        public string Goals { get; set; }
        public string Trainingprogram1 { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public int RegID { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
